export const PokemonData = [
    { name: "Bulbasaur", type: "Grass/Poison" },
    { name: "Ivysaur", type: "Grass/Poison" },
    { name: "Venusaur", type: "Grass/Poison" },
    { name: "Charmander", type: "Fire" },
    { name: "Charmeleon", type: "Fire" },
    { name: "Charizard", type: "Fire/Flying" },
    { name: "Squirtle", type: "Water" },
    { name: "Wartortle", type: "Water" },
    { name: "Blastoise", type: "Water" },
    { name: "Caterpie", type: "Bug" },
    { name: "Metapod", type: "Bug" },
    { name: "Butterfree", type: "Bug/Flying" },
    { name: "Weedle", type: "Bug/Poison" },
    { name: "Kakuna", type: "Bug/Poison" },
    { name: "Beedrill", type: "Bug/Poison" },
    { name: "Pidgey", type: "Normal/Flying" },
    { name: "Pidgeotto", type: "Normal/Flying" },
    { name: "Pidgeot", type: "Normal/Flying" },
    { name: "Rattata", type: "Normal" },
    { name: "Raticate", type: "Normal" },
    { name: "Spearow", type: "Normal/Flying" },
    { name: "Fearow", type: "Normal/Flying" },
    { name: "Ekans", type: "Poison" },
    { name: "Arbok", type: "Poison" },
    { name: "Pikachu", type: "Electric" },
    { name: "Raichu", type: "Electric" },
    { name: "Sandshrew", type: "Ground" },
    { name: "Sandslash", type: "Ground" },
     { name: "Nidoran♀", type: "Poison" },
    { name: "Nidorina", type: "Poison" },
    { name: "Nidoqueen", type: "Poison/Ground" },
    { name: "Nidoran♂", type: "Poison" },
    { name: "Nidorino", type: "Poison" },
    { name: "Nidoking", type: "Poison/Ground" },
    { name: "Clefairy", type: "Fairy" },
    { name: "Clefable", type: "Fairy" },
    { name: "Vulpix", type: "Fire" },
    { name: "Ninetales", type: "Fire" },
    { name: "Jigglypuff", type: "Normal/Fairy" },
    { name: "Wigglytuff", type: "Normal/Fairy" },
    { name: "Zubat", type: "Poison/Flying" },
    { name: "Golbat", type: "Poison/Flying" },
    { name: "Oddish", type: "Grass/Poison" },
    { name: "Gloom", type: "Grass/Poison" },
    { name: "Vileplume", type: "Grass/Poison" },
    { name: "Paras", type: "Bug/Grass" },
    { name: "Parasect", type: "Bug/Grass" },
    { name: "Venonat", type: "Bug/Poison" },
    { name: "Venomoth", type: "Bug/Poison" },
    { name: "Diglett", type: "Ground" }
  ];


  export const imagenes = [
    "../../img/pokemon/Forest1.jpg",
    "../../img/pokemon/Forest3.jpg",
    "../../img/pokemon/Forest4.jpg",
    "../../img/pokemon/Forest5.jpg",
    "../../img/pokemon/Forest6.jpg",
    "../../img/pokemon/Forest7.png",
    "../../img/pokemon/Fire1.jpg",
    "../../img/pokemon/Fire2.jpg",
    "../../img/pokemon/Fire3.png",
    "../../img/pokemon/Fire4.jpg",
    "../../img/pokemon/Fire5.jpg",
    "../../img/pokemon/Fire6.png",
    "../../img/pokemon/Grass1.jpg",
    "../../img/pokemon/Grass2.png",
    "../../img/pokemon/Grass3.jpg",
    "../../img/pokemon/Grass4.jpg",
    "../../img/pokemon/watter1.jpg",
    "../../img/pokemon/watter2.jpg",
    "../../img/pokemon/watter3.jpg",
    "../../img/pokemon/watter4.jpg",
    "../../img/pokemon/watter5.jpg",
    "../../img/pokemon/watter6.jpg",
  ]


